apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: l104-node
  name: l104-node
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "4160"
      port: 4160
      targetPort: 4160
    - name: "4161"
      port: 4161
      targetPort: 4161
    - name: "2404"
      port: 2404
      targetPort: 2404
  selector:
    io.kompose.service: l104-node
