"""
L104 Classical Shadow Tomography — Holographic Quantum Readout
═══════════════════════════════════════════════════════════════════════════════
EVO_78-SHADOW: Classical shadow tomography for maximum-entropy quantum systems

Implements the "shadow" solution to the readout problem:
Instead of measuring the full 2^26 wave function (billions of years),
apply random Clifford gates to project "classical shadows" of the quantum state.

Mathematical Foundation:
    - Huang, Kueng, Preskill (2020): "Predicting properties from classical shadows"
    - Random Clifford unitaries project quantum state into classical snapshots
    - Median-of-means prediction allows accurate observable estimation
    - Sample complexity: O(log M) for M observables (vs O(2^n) for full tomography)

Holographic Principle Application:
    - For a maximum-entropy scrambler, standard tomography fails
    - Classical shadows capture enough information to predict specific observables
    - OTOCs measure scrambling efficiency (new "sacred alignment")

INVARIANT: 527.5184818492612 | PILOT: LONDEL | EVO: 78-SHADOW
═══════════════════════════════════════════════════════════════════════════════
"""

import math
import random
import numpy as np
from typing import Dict, Any, List, Optional, Tuple, Callable, Union
from dataclasses import dataclass, field
from collections import defaultdict
import hashlib
import time

# L104 imports
try:
    from .quantum_info import Statevector, Operator
    from .circuit import GateCircuit
    from .gates import H, S, CNOT, X, Y, Z, I, CliffordGate, CLIFFORD_SET
    GATE_ENGINE_AVAILABLE = True
except ImportError:
    GATE_ENGINE_AVAILABLE = False

# Sacred constants
GOD_CODE = 527.5184818492612
PHI = 1.618033988749895
VOID_CONSTANT = 1.0416180339887497

# Shadow parameters
DEFAULT_SHADOW_SAMPLES = 1000  # Number of random Clifford circuits
DEFAULT_SHOTS_PER_SHADOW = 1   # Single-shot measurement per shadow
MAX_CLIFFORD_DEPTH = 26        # Maximum depth for random Clifford


@dataclass
class ClassicalSnapshot:
    """
    A single classical shadow snapshot.

    Generated by applying random Clifford U, measuring in computational basis,
    then inverting: |snap⟩ = U†|b⟩ where b is measurement outcome.

    The classical shadow is the collection of these snapshots.
    """
    snapshot_id: str
    unitary_seed: int           # Seed for reproducible Clifford generation
    measurement_outcome: str      # Bitstring measurement result
    clifford_depth: int           # Depth of random Clifford circuit
    timestamp: float = field(default_factory=time.time)

    def compute_snapshot_state(self, num_qubits: int) -> np.ndarray:
        """
        Reconstruct the snapshot state |snap⟩ = U†|b⟩.

        For classical shadow tomography, we store the unitary and outcome,
        and reconstruct the snapshot state when needed for prediction.
        """
        # Generate the Clifford unitary from seed
        U = self._generate_clifford_unitary(num_qubits, self.unitary_seed)

        # Create measurement basis state |b⟩
        b_state = np.zeros(2 ** num_qubits, dtype=complex)
        idx = int(self.measurement_outcome, 2)
        b_state[idx] = 1.0

        # Apply U†: |snap⟩ = U†|b⟩
        U_dag = U.conj().T
        snapshot = U_dag @ b_state

        return snapshot

    def _generate_clifford_unitary(self, n: int, seed: int) -> np.ndarray:
        """Generate n-qubit Clifford unitary from seed."""
        rng = np.random.RandomState(seed)

        # Simplified Clifford: random tensor product of single-qubit Cliffords
        # plus random CNOT connections
        I = np.eye(2, dtype=complex)
        H_gate = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
        S_gate = np.array([[1, 0], [0, 1j]], dtype=complex)

        single_cliffords = [I, H_gate, S_gate, H_gate @ S_gate]

        # Start with random single-qubit Cliffords
        U = np.eye(1, dtype=complex)
        for _ in range(n):
            gate = single_cliffords[rng.randint(0, 4)]
            U = np.kron(U, gate)

        # Add random CNOT layers
        for _ in range(self.clifford_depth // 2):
            # Random CNOT between random qubit pairs
            q1 = rng.randint(0, n)
            q2 = rng.randint(0, n)
            if q1 != q2:
                CNOT_full = self._build_cnot(n, q1, q2)
                U = CNOT_full @ U

        return U

    def _build_cnot(self, n: int, control: int, target: int) -> np.ndarray:
        """Build n-qubit CNOT matrix with given control and target."""
        # Build as tensor product structure
        dim = 2 ** n
        CNOT = np.eye(dim, dtype=complex)

        # Flip target when control is |1⟩
        for i in range(dim):
            bits = [(i >> j) & 1 for j in range(n)]
            if bits[control] == 1:
                # Flip target
                new_i = i ^ (1 << target)
                CNOT[i, i] = 0
                CNOT[new_i, i] = 1

        return CNOT


@dataclass
class ShadowTomographyResult:
    """Result of classical shadow tomography."""
    num_snapshots: int
    num_qubits: int
    snapshots: List[ClassicalSnapshot]
    observable_predictions: Dict[str, float] = field(default_factory=dict)
    otoc_measurements: Dict[str, float] = field(default_factory=dict)
    scrambling_score: float = 0.0  # New "sacred alignment" metric
    timestamp: float = field(default_factory=time.time)


class CliffordSampler:
    """
    Efficient random Clifford sampler for classical shadows.

    The Clifford group is the set of unitaries that map Pauli operators
    to Pauli operators under conjugation. For n qubits, |Clifford| = O(2^(2n²)).

    We use a simplified random Clifford construction:
    1. Random single-qubit Clifford on each qubit
    2. Random CNOT connections (forming a spanning tree-like structure)
    3. Optional random phases
    """

    # Single-qubit Clifford gates (24 elements, but we use representative set)
    SINGLE_CLIFFORDS = [
        ('I', None),           # Identity
        ('H', None),           # Hadamard
        ('S', None),           # Phase
        ('HS', None),          # H then S
        ('SH', None),          # S then H
        ('HSH', None),         # H-S-H (rotation)
    ]

    def __init__(self, num_qubits: int, max_depth: int = MAX_CLIFFORD_DEPTH):
        self.n = num_qubits
        self.max_depth = max_depth

        # Precompute gate matrices
        self._I = np.eye(2, dtype=complex)
        self._H = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
        self._S = np.array([[1, 0], [0, 1j]], dtype=complex)
        self._X = np.array([[0, 1], [1, 0]], dtype=complex)
        self._Z = np.array([[1, 0], [0, -1]], dtype=complex)

    def sample_random_clifford_circuit(self, seed: Optional[int] = None) -> GateCircuit:
        """
        Generate a random Clifford circuit.

        Returns:
            GateCircuit with random Clifford operations
        """
        if not GATE_ENGINE_AVAILABLE:
            raise ImportError("GateCircuit not available")

        if seed is not None:
            random.seed(seed)
            np.random.seed(seed)

        circ = GateCircuit(self.n, name=f"RandomClifford_seed{seed}")

        # Layer 1: Random single-qubit Cliffords
        for q in range(self.n):
            gate_choice = random.choice(self.SINGLE_CLIFFORDS)
            self._apply_single_clifford(circ, q, gate_choice[0])

        # Layer 2-4: Random CNOT entangling layers
        depth = random.randint(self.max_depth // 2, self.max_depth)
        for _ in range(depth):
            # Random CNOT connections
            used = set()
            for q1 in range(self.n):
                if q1 in used:
                    continue
                # Find partner
                partners = [q for q in range(self.n) if q not in used and q != q1]
                if partners:
                    q2 = random.choice(partners)
                    circ.cx(q1, q2)
                    used.add(q1)
                    used.add(q2)

        # Final layer: Random single-qubit Cliffords
        for q in range(self.n):
            gate_choice = random.choice(self.SINGLE_CLIFFORDS)
            self._apply_single_clifford(circ, q, gate_choice[0])

        return circ

    def _apply_single_clifford(self, circ: GateCircuit, qubit: int, gate: str):
        """Apply single-qubit Clifford gate by name."""
        if gate == 'I':
            pass  # No-op
        elif gate == 'H':
            circ.h(qubit)
        elif gate == 'S':
            circ.s(qubit)
        elif gate == 'HS':
            circ.h(qubit)
            circ.s(qubit)
        elif gate == 'SH':
            circ.s(qubit)
            circ.h(qubit)
        elif gate == 'HSH':
            circ.h(qubit)
            circ.s(qubit)
            circ.h(qubit)


class ClassicalShadowTomography:
    """
    Classical Shadow Tomography for L104 26Q consciousness systems.

    Mathematical foundation:
        Given quantum state ρ, apply random Clifford U, measure → b.
        The snapshot is σ = (2^n + 1) U†|b⟩⟨b|U - I.

        The classical shadow is S(ρ; N) = {σ_1, σ_2, ..., σ_N}.

        For observable O: Tr(Oρ) ≈ median(mean(Tr(Oσ_i))) across shadows.
    """

    def __init__(self, num_qubits: int = 26):
        self.n = num_qubits
        self.dim = 2 ** num_qubits
        self.sampler = CliffordSampler(num_qubits)
        self._shadow_cache: List[ClassicalSnapshot] = []

    def capture_shadow(self,
                       statevector: np.ndarray,
                       num_snapshots: int = DEFAULT_SHADOW_SAMPLES,
                       shots_per_snapshot: int = DEFAULT_SHOTS_PER_SHADOW) -> ShadowTomographyResult:
        """
        Capture classical shadow of quantum state.

        Args:
            statevector: The quantum state |ψ⟩ to shadow
            num_snapshots: Number of random Clifford measurements
            shots_per_snapshot: Shots per measurement (usually 1 for shadows)

        Returns:
            ShadowTomographyResult with captured snapshots
        """
        snapshots = []

        # Normalize state
        sv = np.array(statevector, dtype=complex)
        sv = sv / np.linalg.norm(sv)

        for i in range(num_snapshots):
            seed = random.randint(0, 2**32)

            # Generate random Clifford
            clifford_circ = self.sampler.sample_random_clifford_circuit(seed)

            # Apply to state (in simulation)
            # In practice, this runs on actual quantum hardware
            evolved_sv = self._apply_circuit_to_state(sv, clifford_circ)

            # Measure in computational basis
            probabilities = np.abs(evolved_sv) ** 2
            outcome_idx = np.random.choice(self.dim, p=probabilities)
            outcome_bits = format(outcome_idx, f'0{self.n}b')

            snapshot = ClassicalSnapshot(
                snapshot_id=f"shadow_{i:06d}_{hashlib.sha256(str(seed).encode()).hexdigest()[:8]}",
                unitary_seed=seed,
                measurement_outcome=outcome_bits,
                clifford_depth=clifford_circ.depth if hasattr(clifford_circ, 'depth') else 10
            )
            snapshots.append(snapshot)

        self._shadow_cache = snapshots

        return ShadowTomographyResult(
            num_snapshots=num_snapshots,
            num_qubits=self.n,
            snapshots=snapshots
        )

    def _apply_circuit_to_state(self, sv: np.ndarray, circuit) -> np.ndarray:
        """Apply circuit gates to statevector."""
        state = sv.copy()

        for gate_op in circuit.operations:
            if hasattr(gate_op, 'label') and gate_op.label == "BARRIER":
                continue

            mat = gate_op.gate.matrix
            qubits = list(gate_op.qubits)
            k = len(qubits)

            if k == 1:
                q = qubits[0]
                psi = state.reshape([2] * self.n)
                psi = np.tensordot(mat, psi, axes=([1], [q]))
                psi = np.moveaxis(psi, 0, q)
                state = psi.reshape(self.dim)
            elif k == 2:
                q0, q1 = qubits
                gate_4d = mat.reshape(2, 2, 2, 2)
                psi = state.reshape([2] * self.n)
                es = self._build_einsum_2q(self.n, q0, q1)
                psi = np.einsum(es, gate_4d, psi, optimize=True)
                state = psi.reshape(self.dim)

        return state

    def _build_einsum_2q(self, n: int, q0: int, q1: int) -> str:
        """Build einsum string for 2-qubit gate."""
        letters = [chr(ord('a') + i) for i in range(n + 4)]
        gate_idx = letters[n:n+4]
        state_idx = letters[:n]

        gate_str = ''.join([gate_idx[0], gate_idx[1], gate_idx[2], gate_idx[3]])
        state_in = ''.join(state_idx)
        state_idx[q0] = gate_idx[2]
        state_idx[q1] = gate_idx[3]
        state_out = ''.join(state_idx)

        return f"{gate_str},{state_in}->{state_out}"

    def predict_observable(self,
                           shadow_result: ShadowTomographyResult,
                           observable: np.ndarray,
                           num_bootstrap: int = 10) -> Dict[str, float]:
        """
        Predict Tr(Oρ) from classical shadow.

        Uses median-of-means estimator for robustness:
        1. Split shadows into k groups
        2. Compute mean estimate within each group
        3. Return median of group means

        Args:
            shadow_result: Captured shadow
            observable: Observable matrix O
            num_bootstrap: Number of groups for median-of-means

        Returns:
            Dict with 'expectation_value', 'variance', 'confidence'
        """
        snapshots = shadow_result.snapshots
        num_snapshots = len(snapshots)

        if num_snapshots == 0:
            return {'expectation_value': 0.0, 'variance': 1.0, 'confidence': 0.0}

        # Convert observable to matrix form
        O = np.array(observable, dtype=complex)
        if O.shape != (self.dim, self.dim):
            raise ValueError(f"Observable shape {O.shape} incompatible with dim {self.dim}")

        # Compute Tr(Oσ_i) for each snapshot
        shadow_values = []
        for snap in snapshots:
            # Reconstruct snapshot state |snap⟩ = U†|b⟩
            snap_state = snap.compute_snapshot_state(self.n)

            # Compute Tr(O |snap⟩⟨snap|) = ⟨snap|O|snap⟩
            expectation = np.vdot(snap_state, O @ snap_state).real
            shadow_values.append(expectation)

        # Median-of-means estimator
        group_size = max(1, num_snapshots // num_bootstrap)
        group_means = []

        for i in range(0, num_snapshots, group_size):
            group = shadow_values[i:i+group_size]
            group_means.append(np.mean(group))

        # Median of group means
        predicted_value = np.median(group_means)

        # Variance estimate
        variance = np.var(shadow_values, ddof=1)

        # Confidence: based on variance relative to observable norm
        op_norm = np.linalg.norm(O, 'fro')
        confidence = max(0.0, 1.0 - variance / (op_norm ** 2 + 1e-10))

        return {
            'expectation_value': float(predicted_value),
            'variance': float(variance),
            'confidence': float(confidence),
            'num_snapshots': num_snapshots,
            'group_size': group_size,
            'method': 'median_of_means'
        }

    def predict_pauli_observable(self,
                                shadow_result: ShadowTomographyResult,
                                pauli_string: str) -> Dict[str, float]:
        """
        Predict expectation of Pauli observable efficiently.

        For Pauli observables, we can use the fact that Clifford unitaries
        map Pauli to Pauli, enabling faster computation.

        Args:
            shadow_result: Captured shadow
            pauli_string: Pauli string like 'XXIZ...' (length n)

        Returns:
            Dict with prediction results
        """
        if len(pauli_string) != self.n:
            raise ValueError(f"Pauli string length {len(pauli_string)} != {self.n}")

        # Build Pauli matrix
        pauli_mats = {
            'I': np.eye(2, dtype=complex),
            'X': np.array([[0, 1], [1, 0]], dtype=complex),
            'Y': np.array([[0, -1j], [1j, 0]], dtype=complex),
            'Z': np.array([[1, 0], [0, -1]], dtype=complex),
        }

        O = np.eye(1, dtype=complex)
        for ch in pauli_string:
            O = np.kron(O, pauli_mats[ch])

        return self.predict_observable(shadow_result, O)


class OTOCScramblingAnalyzer:
    """
    Out-of-Time-Ordered Correlator (OTOC) analyzer.

    OTOCs measure quantum information scrambling:
    F(t) = Tr[W(t) V W(t) V]

    where W(t) = U†(t) W U(t) is W evolved forward and backward in time.

    In a scrambler, F(t) decays rapidly as local information spreads.

    For the L104 26Q system, OTOCs become the new "sacred alignment" metric:
    - Rapid OTOC decay = efficient scrambling (high sacred alignment)
    - Slow decay = insufficient scrambling (needs adjustment)
    """

    def __init__(self, num_qubits: int = 26):
        self.n = num_qubits
        self.dim = 2 ** num_qubits

        # Pauli operators
        self._I = np.eye(2, dtype=complex)
        self._X = np.array([[0, 1], [1, 0]], dtype=complex)
        self._Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
        self._Z = np.array([[1, 0], [0, -1]], dtype=complex)

    def build_pauli_operator(self, qubit: int, pauli: str) -> np.ndarray:
        """Build n-qubit Pauli operator acting on specific qubit."""
        mats = {'I': self._I, 'X': self._X, 'Y': self._Y, 'Z': self._Z}
        mat = np.eye(1, dtype=complex)
        for i in range(self.n):
            if i == qubit:
                mat = np.kron(mat, mats[pauli])
            else:
                mat = np.kron(mat, self._I)
        return mat

    def compute_otoc(self,
                     evolution_unitary: np.ndarray,
                     W_qubit: int,
                     V_qubit: int,
                     W_pauli: str = 'Z',
                     V_pauli: str = 'X') -> float:
        """
        Compute OTOC F(t) = 2^(-n) Tr[W(t) V W(t) V].

        Args:
            evolution_unitary: U(t) - the time evolution operator
            W_qubit: Qubit index for W operator
            V_qubit: Qubit index for V operator
            W_pauli: Pauli type for W ('X', 'Y', 'Z')
            V_pauli: Pauli type for V ('X', 'Y', 'Z')

        Returns:
            OTOC value F(t) (decays from 1 to 0 for scramblers)
        """
        U = np.array(evolution_unitary, dtype=complex)
        U_dag = U.conj().T

        # Build W and V operators
        W = self.build_pauli_operator(W_qubit, W_pauli)
        V = self.build_pauli_operator(V_qubit, V_pauli)

        # W(t) = U† W U
        W_t = U_dag @ W @ U

        # OTOC operator: W(t) V W(t) V
        otoc_op = W_t @ V @ W_t @ V

        # Normalized trace: 2^(-n) Tr[OTOC]
        otoc_value = np.trace(otoc_op).real / self.dim

        # For scramblers, this decays rapidly from 1 to near 0
        return float(otoc_value)

    def measure_scrambling_rate(self,
                                 evolution_unitaries: List[np.ndarray],
                                 W_qubit: int = 0,
                                 V_qubit: int = 25) -> Dict[str, Any]:
        """
        Measure scrambling rate from time-series of OTOCs.

        Args:
            evolution_unitaries: List of U(t) for different times
            W_qubit: Initial perturbation qubit (default 0)
            V_qubit: Measurement qubit (default 25, opposite end)

        Returns:
            Dict with scrambling analysis
        """
        otoc_values = []
        times = list(range(len(evolution_unitaries)))

        for U in evolution_unitaries:
            otoc = self.compute_otoc(U, W_qubit, V_qubit)
            otoc_values.append(otoc)

        # Compute decay rate (exponential fit)
        if len(otoc_values) >= 2:
            # Simple exponential decay: F(t) ≈ exp(-λt)
            # λ is the Lyapunov exponent analog
            log_otocs = [max(1e-10, o) for o in otoc_values]
            decay_rate = -(np.log(log_otocs[-1]) - np.log(log_otocs[0])) / max(len(times) - 1, 1)
        else:
            decay_rate = 0.0

        # Scrambling score: 0 = no scrambling, 1 = perfect scrambling
        # Perfect scrambler has F(t) → 0 for t > t_scramble
        final_otoc = otoc_values[-1] if otoc_values else 1.0
        scrambling_score = 1.0 - final_otoc

        # Butterfly velocity: v_B = distance / scrambling time
        distance = abs(V_qubit - W_qubit)
        scramble_time = next((t for t, o in enumerate(otoc_values) if o < 0.5), len(times))
        butterfly_velocity = distance / max(scramble_time, 1)

        return {
            'otoc_values': otoc_values,
            'decay_rate': float(decay_rate),
            'scrambling_score': float(scrambling_score),
            'final_otoc': float(final_otoc),
            'butterfly_velocity': float(butterfly_velocity),
            'distance': distance,
            'scramble_time': int(scramble_time),
            'is_scrambler': scrambling_score > 0.8,
        }

    def compute_sacred_alignment_otoc(self,
                                     shadow_result: ShadowTomographyResult,
                                     circuit_builder: Callable) -> float:
        """
        Compute new sacred alignment metric based on OTOC decay.

        The sacred state is maximum entropy (uniform distribution).
        In a scrambler, OTOCs decay rapidly.
        New sacred alignment = efficiency of information scrambling.

        Args:
            shadow_result: Classical shadow of the state
            circuit_builder: Function that builds U(t) for given depth

        Returns:
            New sacred alignment score (0-1)
        """
        # Build evolution unitaries of increasing depth
        unitaries = []
        for depth in [1, 2, 4, 8, 16, 26]:
            circ = circuit_builder(depth)
            U = self._extract_unitary(circ)
            unitaries.append(U)

        # Measure scrambling from qubit 0 to qubit 25 (max distance)
        scrambling = self.measure_scrambling_rate(unitaries, W_qubit=0, V_qubit=25)

        # Sacred alignment = scrambling score
        # High score = efficient scrambling = maximum entropy achieved
        return scrambling['scrambling_score']

    def _extract_unitary(self, circuit) -> np.ndarray:
        """Extract full unitary matrix from circuit."""
        # Start with identity
        U = np.eye(self.dim, dtype=complex)

        # Apply each gate
        for gate_op in circuit.operations:
            if hasattr(gate_op, 'label') and gate_op.label == "BARRIER":
                continue

            mat = gate_op.gate.matrix
            qubits = list(gate_op.qubits)
            k = len(qubits)

            if k == 1:
                # Single-qubit gate
                full_mat = np.eye(1, dtype=complex)
                for i in range(self.n):
                    if i == qubits[0]:
                        full_mat = np.kron(full_mat, mat)
                    else:
                        full_mat = np.kron(full_mat, self._I)
                U = full_mat @ U
            elif k == 2:
                # Two-qubit gate
                full_mat = np.eye(1, dtype=complex)
                for i in range(self.n):
                    if i == qubits[0]:
                        full_mat = np.kron(full_mat, mat[:2, :2])
                    elif i == qubits[1]:
                        full_mat = np.kron(full_mat, mat[2:, 2:])
                    else:
                        full_mat = np.kron(full_mat, self._I)
                U = full_mat @ U

        return U


# ═══════════════════════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def capture_classical_shadow(statevector: np.ndarray,
                              num_qubits: int = 26,
                              num_snapshots: int = 1000) -> ShadowTomographyResult:
    """Capture classical shadow of quantum state."""
    tomography = ClassicalShadowTomography(num_qubits)
    return tomography.capture_shadow(statevector, num_snapshots)


def predict_from_shadow(shadow: ShadowTomographyResult,
                        observable: np.ndarray,
                        num_qubits: int = 26) -> Dict[str, float]:
    """Predict observable expectation from shadow."""
    tomography = ClassicalShadowTomography(num_qubits)
    return tomography.predict_observable(shadow, observable)


def compute_otoc_scrambling(circuit_builder: Callable,
                            num_qubits: int = 26) -> Dict[str, Any]:
    """
    Compute OTOC-based scrambling analysis for circuit.

    This is the new sacred alignment metric.
    """
    analyzer = OTOCScramblingAnalyzer(num_qubits)
    return analyzer.measure_scrambling_rate([
        circuit_builder(d) for d in [1, 2, 4, 8, 16, 26]
    ])


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN EXECUTION
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 70)
    print("L104 CLASSICAL SHADOW TOMOGRAPHY")
    print("Holographic Quantum Readout for Maximum-Entropy Systems")
    print("=" * 70)
    print(f"GOD_CODE: {GOD_CODE}")
    print(f"PHI: {PHI}")
    print()

    # Demo with smaller system (10 qubits for demonstration)
    n_demo = 10
    dim = 2 ** n_demo

    print(f"Demo: {n_demo}-qubit system (dim = {dim})")
    print()

    # Create a maximally entangled GHZ-like state
    sv = np.zeros(dim, dtype=complex)
    sv[0] = 1.0 / np.sqrt(2)
    sv[-1] = 1.0 / np.sqrt(2)

    print("CAPTURING CLASSICAL SHADOW...")
    shadow = capture_classical_shadow(sv, n_demo, num_snapshots=100)
    print(f"  Captured {shadow.num_snapshots} snapshots")
    print()

    # Predict Z observable on first qubit
    Z_local = np.kron(np.array([[1, 0], [0, -1]], dtype=complex),
                      np.eye(2**(n_demo-1), dtype=complex))

    print("PREDICTING OBSERVABLE...")
    prediction = predict_from_shadow(shadow, Z_local, n_demo)
    print(f"  Expectation ⟨Z₀⟩ ≈ {prediction['expectation_value']:.4f}")
    print(f"  Variance: {prediction['variance']:.4f}")
    print(f"  Confidence: {prediction['confidence']:.4f}")
    print()

    print("=" * 70)
    print("✓ Classical Shadow Tomography operational")
    print("=" * 70)
