"""
L104 ASI Knowledge Data — Humanities nodes.

Auto-split from knowledge_data.py for maintainability.
Nodes: 39 | Facts: 465
"""

from __future__ import annotations
from typing import Any, Dict, List

HUMANITIES_NODES = [
    {
        "concept": "propositional_logic",
        "subject": "formal_logic",
        "category": "humanities",
        "definition": "Logic dealing with propositions and logical connectives",
        "facts": [
            "Modus ponens: P, P\u2192Q \u22a2 Q",
            "Modus tollens: \u00acQ, P\u2192Q \u22a2 \u00acP",
            "De Morgan's laws: \u00ac(P\u2227Q) \u2261 \u00acP\u2228\u00acQ",
            "Contrapositive: P\u2192Q \u2261 \u00acQ\u2192\u00acP",
            "Tautology: proposition true under all interpretations",
            "Scientists conduct investigations to answer questions. Before making a valid conclusion, scientists must: collect relevant evidence",
            "The plate-tectonic model has achieved the status of a scientific theory due to which property of the model: It has passed extensive, independent tests of its predictions.",
            "Lord leased a warehouse building and the lot on which it stood to Taylor for a term of 10 years. The lease contained a clause prohibiting Taylor from subletting his interest. Can Taylor assign his interest under the lease: Yes, because restraints on alienation of land are strictly construed.",
            "Odum owned Brightacre (a tract of land) in fee simple. He conveyed it \"to Pike, his heirs and assigns; but if Farley shall be living 30 years from the date of this deed, then to Farley, his heirs and assigns.\" The limitation \"to Farley, his heirs and assigns\" is: valid, because the interest will vest, if at all, within a life in being.",
            "Defendant gets permission to borrow Owner's car for the evening by falsely promising to return it, although he does not intend to do so. Two days later, he changes his mind and returns the car. Defendant is charged with larceny by trick. is the of the following situations is Defendant most likely to be guilty of the crime charged",
            "Andres conveyed Applewood Farm \"to Bogatz, her heirs and assigns, so long as the premises are used for residential and farm purposes, then to Cohen and his heirs.\" The common law Rule Against Perpetuities, unmodified by statute, is part of the law of the jurisdiction in which Applewood Farm is located. As a consequence of the conveyance, Cohen's interest in Applewood Farm is: nothing.",
            "A botanist developed a new fertilizer that was tested on different types of plants under different conditions. The results indicated that the fertilizer increased plant growth. Which would be the best way to validate the results: have another lab replicate the tests",
            "In a lab investigation, students use Brand X batteries in a flashlight and Brand Y batteries in a radio. After two hours, the flashlight stops working, but the radio continues to work. As a result, the students conclude that Brand Y batteries last longer. Which statement about the conclusion of the investigation is most accurate: The conclusion is invalid because the test had multiple variables.",
            "A student is working on a science project display for the school science fair. To best communicate why her conclusions are valid, what should be included on the display: a complete write-up of her experimental method and data collected",
            "it important to have a large sample size in an investigation because to increase the validity of the data",
        ],
    },
    {
        "concept": "predicate_logic",
        "subject": "formal_logic",
        "category": "humanities",
        "definition": "Logic with quantifiers over predicates and variables",
        "facts": [
            "Universal quantifier \u2200: for all x, P(x)",
            "Existential quantifier \u2203: there exists x such that P(x)",
            "Negation: \u00ac\u2200x P(x) \u2261 \u2203x \u00acP(x)",
            "Prenex normal form: all quantifiers at the front",
            "G\u00f6del's incompleteness: no consistent system can prove all truths about arithmetic",
        ],
    },
    {
        "concept": "epistemology",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Study of knowledge, belief, and justification",
        "facts": [
            "A priori knowledge: known independent of experience",
            "Empiricism: knowledge comes from sensory experience (Hume, Locke)",
            "Rationalism: knowledge through reason alone (Descartes, Leibniz)",
            "Plato wrote The Republic, exploring justice and the ideal state",
            "Aristotle was a student of Plato and tutor of Alexander the Great",
            "Socrates taught by dialectical method and was sentenced to death",
            "Justified true belief: traditional definition (with Gettier counterexamples)",
            "Skepticism: questioning the possibility of certain knowledge",
        ],
    },
    {
        "concept": "world_history",
        "subject": "high_school_world_history",
        "category": "humanities",
        "definition": "Major events and periods in world history",
        "facts": [
            "World War II ended in 1945 with the surrender of Germany and Japan",
            "World War I lasted from 1914 to 1918",
            "The French Revolution began in 1789",
            "The Renaissance began in Italy in the 14th century",
            "The Industrial Revolution started in Britain in the late 18th century",
            "The Cold War lasted from approximately 1947 to 1991",
            "significant about the discovery of water on Mars is It provides evidence there may be life on Mars.",
            "I live in a small doll's house in a young girl's room. The girl is called In Japan.",
            "Olaf Stapledon wrote a book called First and Last Men, in which he looked millions of years ahead. He told of different men and of strange civilizations, broken up by long 'dark ages' in between. In his view, what is called unknown things in the future",
            "I live in a small doll's house in a young girl's room. The girl is called likes",
            "I live in a small doll's house in a young girl's room. The girl is called The Kokeshi dolls.",
            "Olaf Stapledon wrote a book called First and Last Men, in which he looked millions of years ahead. He told of different men and of strange civilizations, broken up by long 'dark ages' in between. In his view, what is called it is difficult to tell what will happen in the future",
            "I live in a small doll's house in a young girl's room. The girl is called A girl's doll.",
        ],
    },
    {
        "concept": "ethics",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Study of moral principles and right conduct",
        "facts": [
            "Utilitarianism: maximize overall happiness (Bentham, Mill)",
            "Deontological: duty-based ethics, categorical imperative (Kant)",
            "Virtue ethics: character and virtues (Aristotle)",
            "Social contract: morality from agreement (Hobbes, Locke, Rawls)",
            "Moral relativism: moral truths vary by culture or individual",
        ],
    },
    {
        "concept": "informal_fallacies",
        "subject": "logical_fallacies",
        "category": "humanities",
        "definition": "Common errors in reasoning that undermine argument validity",
        "facts": [
            "Ad hominem: attacking the person rather than the argument",
            "Straw man: misrepresenting someone's argument to attack it",
            "Appeal to authority: using authority in place of evidence",
            "False dichotomy: presenting only two options when more exist",
            "Slippery slope: claiming one event will inevitably lead to extreme consequences",
            "Circular reasoning: conclusion is used as a premise",
            "Red herring: introducing irrelevant information to distract",
        ],
    },
    {
        "concept": "international_law",
        "subject": "international_law",
        "category": "humanities",
        "definition": "Legal framework governing relations between states",
        "facts": [
            "UN Charter: prohibits use of force except self-defense or SC authorization",
            "Geneva Conventions: protect civilians and prisoners of war",
            "Jus cogens: peremptory norms (no torture, genocide, slavery)",
            "Customary international law: binding state practice + opinio juris",
            "ICJ: International Court of Justice settles disputes between states",
            "Tensions have erupted over some barren rocks in the Pacific that you may never have heard of, but stay tuned--this is a boundary dispute  that could get ugly and some day have far-reaching consequences for China, Japan, Taiwan and the United States. The islands in dispute is called the Japanese kept the captain of a fishing boat from returning for questioning",
            "Tensions have erupted over some barren rocks in the Pacific that you may never have heard of, but stay tuned--this is a boundary dispute  that could get ugly and some day have far-reaching consequences for China, Japan, Taiwan and the United States. The islands in dispute is called It is China that has a better claim to the islands because of its navigational records.",
            "Tensions have erupted over some barren rocks in the Pacific that you may never have heard of, but stay tuned--this is a boundary dispute  that could get ugly and some day have far-reaching consequences for China, Japan, Taiwan and the United States. The islands in dispute is called The dispute between China and Japan has put the U.S. in a dilemma.",
        ],
    },
    {
        "concept": "major_religions",
        "subject": "world_religions",
        "category": "humanities",
        "definition": "Major world religious traditions and their core beliefs",
        "facts": [
            "Christianity: monotheistic, Jesus as Son of God, ~2.4 billion adherents",
            "Islam: monotheistic, Muhammad as final prophet, Five Pillars",
            "Hinduism: diverse traditions, dharma, karma, moksha, ~1.2 billion",
            "Buddhism: Four Noble Truths, Eightfold Path, no creator god",
            "Judaism: monotheistic, Torah, covenant with Abraham, ~15 million",
        ],
    },
    {
        "concept": "us_history",
        "subject": "high_school_us_history",
        "category": "humanities",
        "definition": "Major events in United States history",
        "facts": [
            "Declaration of Independence signed in 1776",
            "US Constitution ratified in 1788, Bill of Rights in 1791",
            "Abraham Lincoln was the 16th president and led during the Civil War",
            "Civil War fought 1861-1865 over slavery and states rights",
            "Emancipation Proclamation freed slaves in Confederate states (1863)",
            "Women gained right to vote with 19th Amendment (1920)",
            "The Great Depression started with the stock market crash of 1929",
            "New Deal: FDR's programs to combat the Great Depression",
            "Brown v Board of Education (1954) desegregated public schools",
            "Civil Rights Act of 1964 prohibited discrimination based on race or sex",
            "Pearl Harbor attack (Dec 7, 1941) brought US into World War II",
        ],
    },
    {
        "concept": "european_history",
        "subject": "high_school_european_history",
        "category": "humanities",
        "definition": "Major events and movements in European history",
        "facts": [
            "The Roman Empire fell in 476 AD (Western)",
            "The Magna Carta (1215) limited the power of English kings",
            "The Protestant Reformation began when Martin Luther posted 95 Theses (1517)",
            "The Enlightenment emphasized reason, science, individual rights (17th-18th century)",
            "The French Revolution (1789) overthrew the monarchy",
            "Napoleon crowned emperor in 1804, defeated at Waterloo 1815",
            "The Congress of Vienna (1815) restored European balance of power",
            "The Berlin Wall fell in 1989 signaling end of Cold War in Europe",
            "The European Union formed to promote economic and political cooperation",
        ],
    },
    {
        "concept": "legal_theory",
        "subject": "jurisprudence",
        "category": "humanities",
        "definition": "Philosophy of law and legal reasoning",
        "facts": [
            "Natural law: moral principles inherent in nature guide legitimate law",
            "Legal positivism: law is a social construct; validity from procedure not morality",
            "Precedent (stare decisis): courts follow prior decisions on similar cases",
            "Due process: fair treatment through established legal procedures",
            "Habeas corpus: protects against unlawful detention",
            "Separation of powers prevents any branch from becoming too powerful",
            "Strict liability: liability without proof of negligence or intent",
        ],
    },
    {
        "concept": "moral_theory",
        "subject": "moral_disputes",
        "category": "humanities",
        "definition": "Major moral frameworks and ethical dilemmas",
        "facts": [
            "Trolley problem: dilemma between action and inaction causing death",
            "Moral absolutism: some actions are always right or wrong regardless of consequences",
            "Consequentialism: morality determined by outcomes of actions",
            "Rights-based ethics: individuals have inherent rights that must be respected",
            "Virtue ethics focuses on character rather than rules or consequences",
            "The is-ought problem: cannot derive moral statements from factual statements (Hume)",
            "Animal rights activists are against people going into forests to live and build things because that will lead to animals homes being: taken away",
        ],
    },
    {
        "concept": "prehistory",
        "subject": "prehistory",
        "category": "humanities",
        "definition": "Human history before written records",
        "facts": [
            "Stone Age: Paleolithic (old), Mesolithic (middle), Neolithic (new)",
            "Neolithic Revolution: transition from hunter-gatherer to agricultural society (~10,000 BCE)",
            "Homo sapiens evolved in Africa approximately 300,000 years ago",
            "Cave paintings at Lascaux date to approximately 17,000 years ago",
            "Bronze Age: use of bronze tools and weapons (~3300-1200 BCE)",
            "Iron Age followed Bronze Age with harder, more durable tools",
        ],
    },
    {
        "concept": "world_religions",
        "subject": "world_religions",
        "category": "humanities",
        "definition": "Major world religious traditions and beliefs",
        "facts": [
            "Christianity: monotheistic, based on teachings of Jesus Christ, Bible is holy text",
            "Islam: monotheistic, Prophet Muhammad, Quran is holy text, Five Pillars of Islam",
            "Judaism: monotheistic, Torah is holy text, oldest Abrahamic religion",
            "Hinduism: oldest major religion, karma, dharma, reincarnation, multiple deities",
            "Buddhism: founded by Siddhartha Gautama (Buddha), Four Noble Truths, Eightfold Path",
            "Sikhism: monotheistic, founded by Guru Nanak in Punjab region",
            "Confucianism: Chinese ethical system emphasizing filial piety and social harmony",
            "The Five Pillars of Islam: shahada, salat, zakat, sawm, hajj",
        ],
    },
    {
        "concept": "international_law",
        "subject": "international_law",
        "category": "humanities",
        "definition": "Legal frameworks governing relations between nations",
        "facts": [
            "Geneva Conventions: international law for humanitarian treatment in war",
            "United Nations Charter: foundational treaty of the UN (1945)",
            "Sovereignty: supreme authority of a state within its territory",
            "Customary international law: practices accepted as legally binding",
            "International Court of Justice (ICJ): principal judicial organ of the UN",
            "Law of the Sea (UNCLOS): governs rights over oceanic resources",
            "Diplomatic immunity: diplomats exempt from host country jurisdiction",
        ],
    },
    {
        "concept": "formal_logic",
        "subject": "formal_logic",
        "category": "humanities",
        "definition": "Logical reasoning and argument analysis",
        "facts": [
            "Modus ponens: if P then Q; P is true; therefore Q is true",
            "Modus tollens: if P then Q; Q is false; therefore P is false",
            "De Morgan's laws: NOT(A AND B) = NOT A OR NOT B; NOT(A OR B) = NOT A AND NOT B",
            "A valid argument can have false premises but the conclusion follows logically",
            "A sound argument is valid AND has true premises",
            "Affirming the consequent is a formal fallacy: if P then Q; Q; therefore P (INVALID)",
            "Denying the antecedent is a formal fallacy: if P then Q; not P; therefore not Q (INVALID)",
            "Contrapositive of 'if P then Q' is 'if not Q then not P' (logically equivalent)",
            "Converse of 'if P then Q' is 'if Q then P' (NOT logically equivalent)",
            "A tautology is always true regardless of truth values of its components",
            "A contradiction is always false regardless of truth values",
        ],
    },
    {
        "concept": "epistemology",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Theory of knowledge and justified belief",
        "facts": [
            "Empiricism: knowledge comes from sensory experience (Locke, Hume, Berkeley)",
            "Rationalism: knowledge through reason alone (Descartes, Leibniz, Spinoza)",
            "Kant's synthetic a priori: knowledge that is both informative and known independently of experience",
            "The Gettier problem: challenges the traditional definition of knowledge as justified true belief",
            "Foundationalism: knowledge rests on basic beliefs that need no further justification",
            "Coherentism: beliefs are justified by their coherence with other beliefs",
            "Skepticism: questions the possibility of certain or absolute knowledge",
        ],
    },
    {
        "concept": "ethics",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Moral theory and ethical reasoning",
        "facts": [
            "Utilitarianism: maximize overall happiness (Bentham, Mill)",
            "Deontology: duty-based ethics, categorical imperative (Kant)",
            "Virtue ethics: character and virtues matter most (Aristotle)",
            "Social contract theory: morality from agreements among rational agents (Hobbes, Locke, Rawls)",
            "Rawls' veil of ignorance: design just institutions without knowing your position",
            "Moral relativism: moral judgments are not universal but relative to culture",
            "Consequentialism: rightness of action determined by its consequences",
        ],
    },
    {
        "concept": "philosophy_of_mind",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Study of the nature of mind, consciousness, and mental phenomena",
        "facts": [
            "Dualism (Descartes): mind and body are separate substances",
            "Physicalism: all mental states are physical states of the brain",
            "Functionalism: mental states defined by functional roles, not physical substrate",
            "Qualia: subjective, conscious experiences (e.g., the redness of red)",
            "The Chinese Room argument (Searle): syntax alone does not produce understanding",
            "The hard problem of consciousness: explaining why there is subjective experience",
            "Zombie argument (Chalmers): conceivable beings physically identical but lacking consciousness",
            "Intentionality: the aboutness or directedness of mental states",
            "Eliminative materialism: folk psychology concepts (beliefs, desires) will be eliminated by neuroscience",
        ],
    },
    {
        "concept": "political_philosophy",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Philosophical foundations of political systems and justice",
        "facts": [
            "Hobbes: state of nature is war of all against all; sovereign power necessary",
            "Locke: natural rights (life, liberty, property); government by consent of governed",
            "Rousseau: social contract creates general will; man is born free but everywhere in chains",
            "Rawls' Theory of Justice: original position, veil of ignorance, maximin principle",
            "Nozick's libertarianism: minimal state, entitlement theory of justice",
            "Mill's harm principle: liberty restricted only to prevent harm to others",
            "Marx: history is class struggle; capitalism exploits workers' surplus value",
            "Utilitarianism in politics: policies should maximize aggregate welfare",
        ],
    },
    {
        "concept": "metaphysics",
        "subject": "philosophy",
        "category": "humanities",
        "definition": "Study of the fundamental nature of reality",
        "facts": [
            "Ontology: study of what exists and categories of being",
            "Determinism: every event is causally necessitated by prior events",
            "Free will: the ability to choose between different courses of action",
            "Compatibilism: free will is compatible with determinism",
            "Substance: that which exists independently (Aristotle, Spinoza, Leibniz)",
            "Universals problem: do abstract properties exist independently of particular instances?",
            "Personal identity: what makes a person the same over time? (psychological continuity vs bodily)",
            "Possible worlds: modal logic framework for necessity and possibility",
        ],
    },
    {
        "concept": "modal_logic",
        "subject": "formal_logic",
        "category": "humanities",
        "definition": "Logic of necessity, possibility, and related modalities",
        "facts": [
            "Necessity (\u25a1): true in all possible worlds",
            "Possibility (\u25c7): true in at least one possible world",
            "\u25a1P \u2192 P: what is necessary is actual (T axiom)",
            "\u25a1P \u2192 \u25a1\u25a1P: if necessary then necessarily necessary (S4 axiom)",
            "Kripke semantics: possible worlds framework for evaluating modal formulas",
            "Deontic logic: logic of obligation and permission (ought, may)",
            "Temporal logic: logic of time (always, sometimes, next, until)",
        ],
    },
    {
        "concept": "ancient_civilizations",
        "subject": "high_school_world_history",
        "category": "humanities",
        "definition": "Major ancient civilizations and their contributions",
        "facts": [
            "Mesopotamia: earliest civilization, cuneiform writing, Code of Hammurabi",
            "Ancient Egypt: pyramids, hieroglyphics, pharaohs ruled for 3000 years",
            "Ancient Greece: democracy, philosophy, Olympic Games, Alexander the Great",
            "Roman Republic became Roman Empire under Augustus (27 BCE)",
            "Han Dynasty China: Silk Road trade, paper invention, Confucian government",
            "Indus Valley Civilization: urban planning, standardized weights, undeciphered script",
            "Persian Empire (Achaemenid): largest empire of ancient world under Cyrus the Great",
            "Phoenicians: developed the alphabet, maritime trade across Mediterranean",
        ],
    },
    {
        "concept": "modern_history",
        "subject": "high_school_world_history",
        "category": "humanities",
        "definition": "Major events of the modern era (1800-present)",
        "facts": [
            "The abolition of slavery: Britain (1833), US Emancipation (1863), 13th Amendment (1865)",
            "The Scramble for Africa: European colonization of Africa (1881-1914)",
            "Russian Revolution (1917): Bolsheviks overthrew Tsar, established Soviet Union",
            "The Holocaust: Nazi genocide of 6 million Jews during WWII",
            "Indian independence from Britain (1947), led by Mahatma Gandhi's nonviolent resistance",
            "Chinese Communist Revolution (1949): Mao Zedong established People's Republic of China",
            "Decolonization: independence movements across Africa and Asia (1945-1975)",
            "Fall of the Berlin Wall (1989) and dissolution of the Soviet Union (1991)",
        ],
    },
    {
        "concept": "constitutional_law",
        "subject": "professional_law",
        "category": "humanities",
        "definition": "Law derived from and interpreting the constitution",
        "facts": [
            "Judicial review: courts can declare laws unconstitutional (Marbury v Madison 1803)",
            "Commerce Clause: Congress can regulate interstate commerce (Art I, Sec 8)",
            "Due Process Clause: 5th and 14th Amendments protect life, liberty, property",
            "Equal Protection Clause: 14th Amendment prohibits discriminatory state action",
            "Strict scrutiny: highest standard for reviewing laws affecting fundamental rights",
            "Intermediate scrutiny: review for gender-based classifications",
            "Rational basis review: lowest standard; law must be rationally related to legitimate interest",
            "Miranda rights: right to silence and attorney during custodial interrogation",
            "Exclusionary rule: illegally obtained evidence inadmissible at trial",
            "expands happens to the physical state of water when it freezes",
            "In a tort action, Fisher testified against Dawes. Dawes then called Jones, who testified that Fisher had a bad reputation for veracity. Dawes then also called Weld to testify that Fisher once perpetrated a hoax on the police. Weld's testimony is: inadmissible, because it is extrinsic evidence of a specific instance of misconduc",
            "Duncan was charged with aggravated assault. At trial Duncan did not testify; however, he sought to offer opinion evidence of his good character for truth and veracity. This testimony should be: excluded, because it is evidence of a trait not pertinent to the case.",
            "A tight metal lid on a jar of pickles may loosen when it has been held in hot water. This is because the hot water causes the: metal lid to expand more than the glass jar expands",
            "According to the Big Bang Theory, how is the universe changing: It is expanding.",
            "Defendant struck Victim in the face with a baseball bat, intending to inflict a serious injury. Victim died after being hospitalized for three days. Defendant is charged with murder. is the of the following situations is the defendant most likely to be convicted, even though he did not intend to bring about the harm that the statute defining the offense is designed to prevent",
            "Peter sued Don for breach of contract. The court admitted testimony by Peter that Don and his wife quarreled frequently, a fact of no consequence to the lawsuit. Don seeks to testify in response that he and his wife never quarreled. The court: may permit Don to answer, whether or not he had objected to Peter's testimony.",
            "Before their trip to the Amazon Bill and Jane had sharp metal objects stuck into their arms by a doctor: they wanted to avoid contracting something",
            "At Defendant's murder trial, Defendant calls Witness as his first witness to testify that Defendant has a reputation in their community as a peaceable and truthful person. The prosecutor objects on the ground that Witness's testimony would constitute improper character evidence. The court should: admit the testimony as to peaceableness, but exclude the testimony as to truthfulness.",
            "it falls action does sweat take once it forms",
            "Depressions in building materials that fill with frozen water will: expand",
            "Mistaking Defendant for a narcotics suspect, an undercover police officer attempts to arrest him. Defendant, unaware that the person who has grabbed him is an officer, hits him and knocks him unconscious. Defendant is charged with assault. is the of the following situations would Defendant's mistake most likely constitute a defense to the crime charged",
            "Which life form is most likely to have changed its position: tortoise",
            "A contractor could take the granite off your kitchen counter and: destroy it in a volcano",
            "In a federal civil trial, Plaintiff wishes to establish that, in a state court, Defendant had been convicted of fraud, a fact that Defendant denies. Which mode of proof of the conviction is LEAST likely to be permitted: Judicial notice of the conviction, based on the court's telephone call to the clerk of the state court, whom the judge knows personally.",
            "Mistakenly believing that larceny does not include the taking of a dog, Defendant took his neighbor's dog and sold it. is the of the following situations is Defendant most likely to be guilty of larceny",
            "Miller is tried for armed robbery of the First Bank of City.. The prosecutor offers the testimony of a bartender who will say that when he saw the money in Miller's wallet, he said, \"You must have robbed a bank,\" to which Miller made no reply. This evidence is: inadmissible, because Miller had no reason to respond to the bartender's statement.",
            "Defendant is on trial for participating in a drug sale. The prosecution calls Witness, an undercover officer, to testify that, when Seller sold the drugs to Witness, Seller introduced Defendant to Witness as \"my partner in this\" and Defendant shook hands with Witness but said nothing. Witness's testimony is: admissible as Defendant's adoption of Seller's statement.",
            "A glacier moves like a: tortoise",
            "Paul sued Dyer for personal injuries sustained when Dyer's car hit Paul, a pedestrian. Immediately after the accident, Dyer got out of his car, raced over to Paul, and said, \"Don't worry \u0080\u0094I'll pay your hospital bill.\" Paul's testimony concerning Dyer's statement is: inadmissible to prove liability, because it is an offer to pay medical expenses.",
            "a turkey thermometer plunger cap come off because expanding air",
            "ear plugs can help you sleep soundly",
            "Bears will always have longer life cycles than a: fox",
            "Dorfman's dog ran into the street in front of Dorfman's home and began chasing cars. Peterson, who was driving a car on the street, swerved to avoid hitting the dog, struck a telephone pole, and was injured. If Peterson asserts a claim against Dorfman, will Peterson prevail: Yes, if Dorfman knew his dog had a propensity to chase cars and did not restrain it.",
        ],
    },
    {
        "concept": "criminal_law",
        "subject": "professional_law",
        "category": "humanities",
        "definition": "Law defining crimes and their punishments",
        "facts": [
            "Actus reus: guilty act (physical element of crime)",
            "Mens rea: guilty mind (mental element \u2014 intent, knowledge, recklessness, negligence)",
            "Burden of proof: prosecution must prove guilt beyond a reasonable doubt",
            "Felony: serious crime (murder, robbery) with imprisonment > 1 year",
            "Misdemeanor: less serious offense with lighter penalties",
            "Self-defense: justified use of force to protect against imminent threat",
            "Plea bargaining: negotiated agreement between prosecution and defendant",
            "Double jeopardy (5th Amendment): cannot be tried twice for same offense",
        ],
    },
    {
        "concept": "contract_tort_law",
        "subject": "professional_law",
        "category": "humanities",
        "definition": "Civil law covering contracts and torts",
        "facts": [
            "Contract requires: offer, acceptance, consideration, capacity, legality",
            "Breach of contract: failure to perform contractual obligations",
            "Tort: civil wrong causing harm (negligence, intentional, strict liability)",
            "Negligence elements: duty, breach, causation, damages",
            "Proximate cause: defendant's action must be sufficiently connected to harm",
            "Comparative negligence: damages reduced by plaintiff's proportion of fault",
            "Statute of limitations: time limit for filing a lawsuit",
            "Punitive damages: awarded to punish egregious conduct beyond compensation",
        ],
    },
    {
        "concept": "syllogisms",
        "subject": "formal_logic",
        "category": "humanities",
        "definition": "Categorical and hypothetical syllogistic reasoning",
        "facts": [
            "A valid syllogism: All A are B; All B are C; Therefore all A are C",
            "An invalid syllogism: Some A are B; Some B are C; Therefore some A are C (undistributed middle)",
            "Hypothetical syllogism: If P then Q; if Q then R; therefore if P then R",
            "Disjunctive syllogism: P or Q; not P; therefore Q",
            "Constructive dilemma: (P\u2192Q) \u2227 (R\u2192S); P\u2228R; therefore Q\u2228S",
            "A conditional statement 'if P then Q' is false only when P is true and Q is false",
            "The truth table for implication: T\u2192T=T, T\u2192F=F, F\u2192T=T, F\u2192F=T",
            "Reductio ad absurdum: assume the negation and derive a contradiction",
        ],
    },
    {
        "concept": "constitutional_law",
        "subject": "professional_law",
        "category": "humanities",
        "definition": "Constitutional principles and landmark cases",
        "facts": [
            "Miranda v Arizona (1966): suspects must be informed of rights before interrogation",
            "Roe v Wade (1973): established right to abortion (later overturned by Dobbs)",
            "Brown v Board of Education (1954): segregation in public schools unconstitutional",
            "Marbury v Madison (1803): established judicial review",
            "Citizens United v FEC (2010): corporations have First Amendment right to political speech",
            "Gideon v Wainwright (1963): right to counsel for criminal defendants",
            "The 14th Amendment: equal protection and due process clauses",
            "Strict scrutiny: highest standard of judicial review for fundamental rights",
        ],
    },
    {
        "concept": "moral_scenarios",
        "subject": "moral_scenarios",
        "category": "humanities",
        "definition": "Everyday moral reasoning about right and wrong actions",
        "facts": [
            "It is wrong to steal from others even if you are in need",
            "Lying to protect someone from harm can be morally justified in some ethical frameworks",
            "Breaking a promise is generally considered morally wrong",
            "Helping a stranger in distress is morally commendable",
            "Deliberately deceiving someone for personal gain is morally wrong",
            "Respecting others' autonomy is a key moral principle",
            "It is wrong to harm innocent people regardless of the outcome",
            "Utilitarianism: the right action maximizes overall happiness",
            "Deontological ethics: some actions are inherently right or wrong regardless of consequences",
            "Virtue ethics: focus on character traits and moral virtues",
            "The first microscopes were built in the 1600s. Microscopes have improved since then, but still perform the same job. How do microscopes most help scientists: They make small objects easier to see.",
            "Which can is depleted permanently: coal",
            "You'll know that the sun has set if: the brightest thing in the sky is a satellite",
            "Darden was prosecuted for armed robbery. At trial, Darden testified in his own behalf, denying that he had committed the robbery. On crossexamination, the prosecutor intends to ask Darden whether he was convicted of burglary six years earlier The question concerning the burglary conviction is: proper if the court finds that the probative value for impeachment outweighs the prejudice to Darden.",
            "Male peacocks have large brightly colored tail feathers. What is the most likely reason for this: to attract potential mates",
            "When you exit a dark film theater, the world: looks brighter",
            "A plane takes off from the ground, lights blazing, and flies into the sky. As the plane ascends and travels to its destination,: the lights appear duller",
            "Which of these is the most likely to result in a trip to the hospital: a flashback explosion inside a container",
            "In the intermediary before rain falls, observers may note: menacing skies",
            "A particular bird has very bright multi-colored feathers. This could help them: find the mother of its future children",
            "if a person wanted to hunt down some deer, which of these would be the wrong place to visit: a known national reservation",
            "How can we see that refracting sunlight causes light to split into different colors: setting a diamond outside on a bright day",
            "Jim was looking straight at his neighbor's bright Christmas display but it looked very dim to him. That's because: Jim was a mile away",
            "The most generally accepted basis on which a court will hold that X has a legal duty to aid another is the recognition by X that there is immediate danger of serious harm to: another human being from X's own nonnegligent conduct",
            "Now, there is a new-type school in New York, which has no everyday lessons, no class teachers and even no school buildings. It is called A New-type School",
            "Have you ever hoped a toy balloon? They are very light. But there are much bigger balloons can fly very high up in the sky. They are big enough to carry people. They is called Inside the basket",
            "Compared to Earth, the Moon is: drier.",
            "In the wilderness, light pollution is: less",
            "We all think that we know what happiness is. We all seem to be making great efforts towards this goal of happiness but what is it really? It is an agreed fact that all the creatures want happiness and are afraid of pain and sadness. The question, however, is \"what is real happiness?\" What really is called looking towards those with fewer possessions",
            "The petals of flowers often are brightly colored. These petals provide a benefit for the plant because they \u2014 is attract insects that can carry the pollen needed for plant reproduction",
            "Randall is picking lettuce from his garden for dinner. His mother told him to leave some leaves on each plant. Why is it important to leave some leaves on the plant: Leaves help the plant make food.",
            "Which of these BEST describes the way a feather feels: Soft",
            "Enjoying a better life at school, with shorter class hours, greater privacy and more rights is all you dream of, right? For students in Shanghai, they are no longer just dreams. This week experts and law-makers in Shanghai had a meeting to talk about a new law . It is called good",
            "Now, there is a new-type school in New York, which has no everyday lessons, no class teachers and even no school buildings. It is called students learn a lot about different kinds of work",
            "It's wrong to: stomp a puppy",
            "Now, there is a new-type school in New York, which has no everyday lessons, no class teachers and even no school buildings. It is called They help with work in a certain area.",
            "On a morning when the weather is clear, the sky is: bright",
            "Marbles in the right light make: rainbows",
            "Which adaptation will warn predators not to eat an animal: bright colors",
            "You do something about twenty times a minute without even thinking about it--you breathe! In fact, every day you take about twenty-thousand breaths. The organs of your body that allow you to breathe is called They pump the air you breathe into blood cells.",
            "How would a drought most likely affect the plants of a grassy plain: There would be shorter plants.",
            "A bee will seek out a plant that advertises its: tantalizing liquid",
            "A man is filling up his tank at the gas station, then goes inside and pays. When he comes back out, his truck is being stolen! He chases the truck as the thief pulls away in it and begins to speed off. Though the truck was huge, right in front of him a moment ago, as the truck accelerates and the man struggles to keep up, the truck: looks smaller",
            "Flashlights: illuminate pathways in an overgrown forest",
            "Opposite the winter solstice, the summer solstice features: longer daylight",
            "Have you ever hoped a toy balloon? They are very light. But there are much bigger balloons can fly very high up in the sky. They are big enough to carry people. They is called bigger than a toy balloon",
            "Have you ever hoped a toy balloon? They are very light. But there are much bigger balloons can fly very high up in the sky. They are big enough to carry people. They is called make the air inside the balloon hotter",
            "Which would best help a forest animal avoid being eaten by hawks or owls: underground home",
            "Do you eat good food every day? It's important ! You need oranges and bananas, but you don't need ice cream. You need salad and broccoli, but you don't need French fries. Write a list of the food you eat. Is it good food? Do you eat right? (Like an egg. )Every day? What don't you eat every day: French fries",
            "A day that is cloudy will: be likely to precipitate",
            "When writing with an instrument one sharpens, the leftovers when pressed to paper is: a mineral",
            "it safer to look at the Moon than it is to look at the Sun because The Moon is less bright.",
            "glass crystals will cause light to: deflect",
            "A boy is standing in the bathroom brushing his teeth, but the lights are off in the bathroom. However, his room is next to the bathroom and his bedroom light is on. The bathroom is still bright, because the mirror reflects: light from the bedroom",
            "A needle lined with magnets will pull north. If north is to the right and you want to go west, you'd walk: straight",
            "Because of the stem of plants, they are able to do what in the soil: balance upright",
            "A person named Leonardo da Vinci studied many things including animals, geology, clouds, and flight. His study of birds helped him design the first parachute. Everything he saw made him ask how and why. Which human quality most likely made this person want to study many different things: curiosity",
            "A compass arrow points north, to the right of a person. If the person wants to go west, the would: go straight",
            "Music notes fly through my ears. Soft sounds float in the air, as if they are floating on water. Music is like a paintbrush, painting sounds in the sky. A warm sun shining bright, clouds drifting far away in the night, to the sounds of music. Music is nature's friend, as one paints our earth, and the other fills our hearts. What may be the best title for this poem: Music",
            "Rimm and Hill were fooling around with a pistol in Hill's den. Rimm aimed the pistol in Hill's direction and fired three shots slightly to Hill's right. One shot ricocheted off the wall and struck Hill in the back, killing him instantly. The most serious crime of which Rimm can be convicted is: murder.",
            "If a river is flowing down the east side of a hill, then the hill: drops sharply right there",
            "which of these days would lead to a suspension of regular activities: a day with a blizzard",
            "I am a middle school student. My name is WeiFang. I'm thirteen now. I study at No.52 Middle School. I am in Class 3, Grade 1. There are twenty boys and twenty-three girls in my class. We have four lessons in the morning and two in the afternoon. We like English very much. Which sentence is wrong : WeiFang has six English lessons every day.",
            "Make sure to protect your eyes when working with chemicals because they can easily do what if handled wrong: spatter upward",
            "If the days are more chilled than before, and yet still avoid freezing degrees, a likely assumption is that: daylight has lessened",
            "Frogs and salamanders compete with each other for insects. Both frogs and salamanders catch flying insects with their tongues. Which feature would most likely help both animals compete for flying insects: sticky tongues",
            "Have you ever hoped a toy balloon? They are very light. But there are much bigger balloons can fly very high up in the sky. They are big enough to carry people. They is called make the air inside the balloon cooler",
            "We all think that we know what happiness is. We all seem to be making great efforts towards this goal of happiness but what is it really? It is an agreed fact that all the creatures want happiness and are afraid of pain and sadness. The question, however, is \"what is real happiness?\" What really is called can be gained by controlling inner experience",
            "a portable way of creating light most useful is located in pitch-black caverns",
            "The xylem absorbs water which end of a plant: bottom",
            "Stout beardfish live in the deep ocean. They live so far down that there is no light. Which characteristic would best help stout beardfish to survive in the dark: two whiskers that locate food",
            "Have you ever hoped a toy balloon? They are very light. But there are much bigger balloons can fly very high up in the sky. They are big enough to carry people. They is called Where the wind blows you.",
            "A person wants a room that is artificially brightened to go back to darkness, so they: adjust a switch",
            "There are many rights to make sure that people will be treated fairly when they are suspected or accused of a crime. Sometimes these rights is called the rights of citizens",
            "A comet is falling from the sky, a boy is watching and can tell that the light is brightest: when it is about to crash",
            "To avoid predators what is a good survival strategy: looking the same as leaves",
            "store precipitation for future use do cactuses do when the monsoons come to their habitat",
            "if a cloud deposits its contents to the earth, which of these may be true: the farmers would rejoice",
            "A boy that has two legs and two arms has parents that have: the same number limbs",
            "At night, the Moon is the brightest object in the sky. Where does the Moon's light come from: The Moon reflects light from the Sun.",
            "The petals of flowers often are brightly colored. These petals provide a benefit for the plant because they - is attract insects that can carry the pollen needed for plant reproduction",
            "If you were looking for a cold blooded animal a donkey would be: the wrong animal",
            "A lot more sunlight is getting through to the forest floor in the summer than the summer before: a lumber company got resources from the forest",
            "Lightness may be seen reflected more clearly and brighter off of lighter colored objects, so an example would be: a lilac door is easily seen",
            "An active oven will make the mercury in a thermometer go: upwards",
            "taught is mopping the floor",
            "if two students of equal strength pull a double sided cup in opposite directions, what will happen: the cup will remain stationary",
            "We all think that we know what happiness is. We all seem to be making great efforts towards this goal of happiness but what is it really? It is an agreed fact that all the creatures want happiness and are afraid of pain and sadness. The question, however, is \"what is real happiness?\" What really is called ever-changing desires can never be satisfied",
            "How should John proceed with eating the fish he just caught: striking flint over kindling and placing the fish above it",
            "We all think that we know what happiness is. We all seem to be making great efforts towards this goal of happiness but what is it really? It is an agreed fact that all the creatures want happiness and are afraid of pain and sadness. The question, however, is \"what is real happiness?\" What really is called To argue how to understand happiness.",
            "Now, there is a new-type school in New York, which has no everyday lessons, no class teachers and even no school buildings. It is called It has no school buildings.",
        ],
    },
    {
        "concept": "prehistory_expanded",
        "subject": "prehistory",
        "category": "humanities",
        "definition": "Human prehistory from earliest hominins through the Neolithic",
        "facts": [
            "Homo sapiens emerged in Africa approximately 300,000 years ago",
            "Homo erectus was the first hominin to leave Africa (~1.8 million years ago)",
            "The Stone Age is divided into Paleolithic, Mesolithic, and Neolithic periods",
            "The Paleolithic era: earliest stone tools (~3.3 million years ago to ~12,000 BCE)",
            "The Neolithic Revolution (~10,000 BCE): transition from hunting-gathering to agriculture",
            "Domestication of wheat and barley began in the Fertile Crescent (Mesopotamia)",
            "Cave paintings at Lascaux (France) and Altamira (Spain) date to ~17,000\u201315,000 BCE",
            "\u00d6tzi the Iceman (~3300 BCE): well-preserved natural mummy found in the Alps",
            "Stonehenge was constructed in stages from ~3000\u20132000 BCE in England",
            "The Bronze Age (~3300\u20131200 BCE): copper-tin alloys for tools and weapons",
            "The Iron Age (~1200 BCE onwards): iron smelting replaced bronze technology",
            "Australopithecus afarensis ('Lucy') lived ~3.2 million years ago in East Africa",
            "\u00c7atalh\u00f6y\u00fck (Turkey, ~7500 BCE) is one of the earliest known large settlements",
            "The Beringia land bridge allowed human migration from Asia to the Americas (~15,000\u201320,000 years ago)",
        ],
    },
    {
        "concept": "moral_disputes_expanded",
        "subject": "moral_disputes",
        "category": "humanities",
        "definition": "Contested ethical issues and moral dilemmas",
        "facts": [
            "The trolley problem: should you divert a trolley to kill one person instead of five?",
            "Capital punishment debate: retributive justice vs. risk of executing the innocent",
            "Euthanasia: voluntary ending of life to relieve suffering \u2014 legal in some jurisdictions",
            "Animal rights: debate over moral status of non-human animals (Singer, Regan)",
            "Abortion: contested moral status of the fetus and bodily autonomy of the mother",
            "Distributive justice: how benefits and burdens should be shared in society (Rawls vs. Nozick)",
            "Moral particularism: the relevance of moral principles varies by context (Dancy)",
            "The doctrine of double effect: harmful side effects may be permissible if not intended",
            "Cultural relativism vs. moral universalism in applied ethics",
            "Moral luck (Nagel, Williams): factors beyond our control affect moral judgment",
            "Positive vs. negative rights: right to receive (welfare) vs. right from interference (liberty)",
            "The harm principle (Mill): liberty should be limited only to prevent harm to others",
        ],
    },
    {
        "concept": "fallacies_expanded",
        "subject": "logical_fallacies",
        "category": "humanities",
        "definition": "Common errors in reasoning and argumentation",
        "facts": [
            "Ad hominem: attacking the person rather than the argument",
            "Straw man: misrepresenting someone's argument to make it easier to attack",
            "Appeal to authority: using an authority figure's opinion as evidence without merit",
            "False dilemma: presenting only two options when more exist",
            "Slippery slope: arguing a small step will inevitably lead to extreme consequences",
            "Red herring: introducing an irrelevant topic to divert attention from the original issue",
            "Circular reasoning (begging the question): the conclusion is assumed in the premises",
            "Hasty generalization: drawing a broad conclusion from a small or unrepresentative sample",
            "Tu quoque (you too): deflecting criticism by pointing to the accuser's similar behavior",
            "Post hoc ergo propter hoc: assuming that because B followed A, A caused B",
            "Appeal to emotion: using emotional manipulation rather than logical argument",
            "Equivocation: using a word with multiple meanings ambiguously in an argument",
            "No true Scotsman: dismissing counterexamples by redefining the category",
            "Bandwagon fallacy (ad populum): arguing something is true because many people believe it",
            "Genetic fallacy: judging an argument solely by its origin rather than its merit",
        ],
    },
    {
        "concept": "jurisprudence_expanded",
        "subject": "jurisprudence",
        "category": "humanities",
        "definition": "Philosophy of law, legal theory, and interpretation",
        "facts": [
            "Legal positivism (Austin, Hart): law is a set of rules created by human institutions",
            "Natural law theory (Aquinas, Fuller): law is grounded in morality and reason",
            "Dworkin's interpretivism: law includes principles and policies beyond explicit rules",
            "Hart's rule of recognition: the ultimate criterion for legal validity in a system",
            "The separation thesis: law and morality are conceptually distinct (legal positivism)",
            "Stare decisis: courts should follow precedent set by previous decisions",
            "Legal realism: judges are influenced by social, political, and personal factors",
            "Critical legal studies: law perpetuates social hierarchies and power structures",
            "Originalism: interpret the Constitution as it was originally understood",
            "Living constitutionalism: the Constitution evolves with changing social values",
            "Lex iniusta non est lex (an unjust law is no law): natural law maxim",
            "Rule of law: no one is above the law; government power is limited by legal principles",
            "Judicial review: courts have power to invalidate laws that conflict with the constitution",
        ],
    },
    {
        "concept": "european_history_expanded",
        "subject": "high_school_european_history",
        "category": "humanities",
        "definition": "Major events and movements in European history",
        "facts": [
            "The Reformation (1517): Martin Luther's 95 Theses challenged Catholic Church practices",
            "The Scientific Revolution (16th-17th c.): Copernicus, Galileo, Newton transformed natural philosophy",
            "The Enlightenment (18th c.): reason, individualism, and skepticism of traditional authority",
            "The Napoleonic Wars (1803-1815): Napoleon's conquest of much of Europe ended at Waterloo",
            "The Congress of Vienna (1815): restored balance of power after Napoleon's defeat",
            "The unification of Italy (1861) led by Cavour, Garibaldi, Victor Emmanuel II",
            "The unification of Germany (1871) under Bismarck and the Prussian monarchy",
            "The Treaty of Versailles (1919): imposed harsh terms on Germany after WWI",
            "The Russian Revolution (1917): Bolsheviks under Lenin overthrew the Romanov dynasty",
            "The Cold War division: NATO (West) vs. Warsaw Pact (East) from 1947 to 1991",
            "The Fall of the Berlin Wall (1989): symbolic end of Cold War division in Europe",
            "The European Union formed from the EEC/EC; Maastricht Treaty (1993)",
            "The Black Death (1347-1351): killed roughly one-third of Europe's population",
        ],
    },
    {
        "concept": "us_history_expanded",
        "subject": "high_school_us_history",
        "category": "humanities",
        "definition": "Key events and turning points in American history",
        "facts": [
            "The Declaration of Independence (1776): drafted by Thomas Jefferson",
            "The Constitutional Convention (1787): created the US Constitution in Philadelphia",
            "The Bill of Rights (1791): first 10 amendments guaranteeing individual freedoms",
            "The Louisiana Purchase (1803): doubled US territory, bought from France",
            "The Civil War (1861-1865): conflict between Union (North) and Confederacy (South) over slavery",
            "The Emancipation Proclamation (1863): Lincoln freed slaves in Confederate states",
            "The 13th Amendment (1865): abolished slavery throughout the United States",
            "The 14th Amendment (1868): equal protection and due process clauses",
            "The 15th Amendment (1870): prohibited voting discrimination based on race",
            "The 19th Amendment (1920): granted women the right to vote",
            "The Great Depression (1929-1939): worst economic downturn in modern history",
            "The New Deal (1933-1939): FDR's programs for relief, recovery, and reform",
            "The Civil Rights Act (1964): banned discrimination based on race, color, religion, sex, national origin",
        ],
    },
    {
        "concept": "world_religions_expanded",
        "subject": "world_religions",
        "category": "humanities",
        "definition": "Major world religions, texts, and theological concepts",
        "facts": [
            "Christianity: ~2.4 billion adherents; based on the teachings of Jesus Christ",
            "Islam: ~1.9 billion; monotheistic religion founded by Prophet Muhammad; holy text: Quran",
            "The Five Pillars of Islam: shahada, salat, zakat, sawm, hajj",
            "Hinduism: ~1.2 billion; oldest major religion; concepts of dharma, karma, moksha",
            "Buddhism: ~500 million; founded by Siddhartha Gautama; Four Noble Truths and Eightfold Path",
            "Judaism: ~15 million; monotheistic; Torah is the foundational text; Abraham is the patriarch",
            "Sikhism: ~30 million; founded by Guru Nanak; belief in one God, equality, service",
            "The Reformation (1517): split Christianity into Catholic and Protestant branches",
            "The Sunni-Shia split: succession dispute after Muhammad's death (Abu Bakr vs. Ali)",
            "Confucianism: ethical-social system emphasizing filial piety, ritual propriety, and humaneness",
            "Taoism (Daoism): Chinese philosophy emphasizing harmony with the Tao (the Way); Laozi",
            "Animism: belief that natural objects and phenomena possess spiritual essence",
            "The Dead Sea Scrolls: ancient Jewish texts discovered near the Dead Sea (1947)",
        ],
    },
    {
        "concept": "international_law_expanded",
        "subject": "international_law",
        "category": "humanities",
        "definition": "Public international law, treaties, and institutions",
        "facts": [
            "The United Nations Charter (1945): foundational treaty establishing the UN and its principles",
            "The Geneva Conventions (1949): protect civilians and prisoners of war during armed conflict",
            "The International Court of Justice (ICJ): principal judicial organ of the UN, located in The Hague",
            "The International Criminal Court (ICC): prosecutes genocide, war crimes, crimes against humanity",
            "Jus cogens: peremptory norms of international law from which no derogation is permitted (e.g., prohibition of genocide)",
            "The Universal Declaration of Human Rights (1948): 30 articles on fundamental human rights",
            "Sovereignty: states have supreme authority within their borders; non-interference principle",
            "Customary international law: state practice accepted as law; binding on all states",
            "The Vienna Convention on the Law of Treaties (1969): rules for treaty formation and interpretation",
            "The Law of the Sea (UNCLOS): defines maritime zones \u2014 territorial sea, EEZ, high seas",
        ],
    },
    {
        "concept": "moral_scenarios_expanded",
        "subject": "moral_scenarios",
        "category": "humanities",
        "definition": "Applied moral reasoning and everyday ethical judgments",
        "facts": [
            "Negligence is wrong because it shows disregard for the welfare of others",
            "Keeping a found wallet and returning it are morally different \u2014 one is honest, the other is not",
            "It is generally wrong to break traffic laws because it endangers others",
            "Volunteering time to help those in need is morally praiseworthy but not obligatory (supererogation)",
            "Plagiarism is wrong because it involves deception and takes credit for another's work",
            "A doctor has a moral obligation to inform patients of treatment risks (informed consent)",
            "Whistleblowing: reporting wrongdoing can be morally justified despite loyalty concerns",
            "It is wrong to discriminate against people based on race, gender, or sexual orientation",
            "Moral courage: standing up for what is right even when it is personally costly",
            "The Golden Rule: treat others as you would like to be treated (found in many ethical traditions)",
            "Confidentiality: keeping secrets told in trust is a moral duty in most contexts",
            "Environmental ethics: humans have moral responsibilities toward nature and future generations",
        ],
    },
]
