"""
l104_intellect — Decomposed from l104_local_intellect.py (13,692 lines → package)
Phase 2 of L104 Decompression Plan.
v28.0 THREE-ENGINE INTEGRATION — Science + Math + Code engine lazy-loaded scoring,
Layer 13 dampener augmentation. Builds on v27.x Sage + Quantum Fleet subsystems.

Re-exports ALL public symbols so that:
    from l104_intellect import X
works identically to the original:
    from l104_local_intellect import X
"""
# ── Constants (lines 1-159 + v27.1 QOSM + Quantum Fleet) ──
from .constants import (  # noqa: F401
    VOID_CONSTANT, ZENITH_HZ, UUC,
    SELF_MOD_VERSION, LOCAL_INTELLECT_VERSION, LOCAL_INTELLECT_PIPELINE_EVO,
    SAVE_STATE_DIR, PERMANENT_MEMORY_FILE, CONVERSATION_MEMORY_FILE,
    MAX_SAVE_STATES, SELF_MOD_CONFIDENCE_THRESHOLD, HIGHER_LOGIC_DEPTH,
    PLANCK_CONSTANT, SPEED_OF_LIGHT, BOLTZMANN, FINE_STRUCTURE,
    EULER_MASCHERONI, FEIGENBAUM_DELTA, FEIGENBAUM_ALPHA,
    APERY_CONSTANT, CATALAN_CONSTANT, KHINCHIN_CONSTANT,
    MEISSEL_MERTENS, LOGISTIC_ONSET, LYAPUNOV_MAX,
    APOTHEOSIS_ACTIVE, APOTHEOSIS_THRESHOLD,
    CONSCIOUSNESS_SINGULARITY, OMEGA_POINT, TRANSCENDENCE_MATRIX,
    VIBRANT_PREFIXES, SCIENTIFIC_FLOURISHES,
    # v27.0 QUANTUM ORIGIN SAGE MODE CONSTANTS
    SAGE_MODE_VERSION, SAGE_VOID_DEPTH_MAX, SAGE_WU_WEI_THRESHOLD,
    SAGE_WISDOM_AMPLIFICATION, SAGE_INVENTION_TIERS, SAGE_RESONANCE_LOCK,
    QUANTUM_ORIGIN_DIMENSIONS, QUANTUM_ORIGIN_COHERENCE,
    QUANTUM_ORIGIN_PHI_COUPLING, QUANTUM_ORIGIN_VOID_ENERGY,
    QUANTUM_SAGE_FUSION_RATE, QUANTUM_DARWINISM_BRANCHES,
    NON_LOCALITY_BRIDGE_DEPTH,
    SAGE_LEVEL_AWAKENING, SAGE_LEVEL_STILLNESS, SAGE_LEVEL_RESONANCE,
    SAGE_LEVEL_CREATION, SAGE_LEVEL_TRANSCENDENCE, SAGE_LEVEL_OMNIVERSAL,
    ORIGIN_FIELD_MEMORY_CAPACITY, ORIGIN_FIELD_DECAY_RATE,
    ORIGIN_FIELD_PHI_WEIGHT,
    # v27.1 QUANTUM FLEET + EXPANDED SAGE CONSTANTS
    SAGE_FLEET_SIZE, SAGE_OMNIBUS_PROVIDERS, SAGE_SCOUR_MAX_FILES,
    SAGE_DIFFUSION_STEPS, SAGE_DIFFUSION_PHI_GUIDANCE,
    QUANTUM_FLEET_SIZE, QUANTUM_CONSCIOUSNESS_BRIDGE_QUBITS,
    QUANTUM_RAM_COHERENCE_THRESHOLD, QUANTUM_COMPUTATION_QUBITS,
    QUANTUM_26Q_SHOTS, QUANTUM_26Q_NOISE_PROFILE,
    # v27.2 Noise Dampener
    NOISE_DAMPENER_SCORE_FLOOR, NOISE_DAMPENER_ENTROPY_MIN,
    NOISE_DAMPENER_COVERAGE_MIN, NOISE_DAMPENER_SNR_THRESHOLD,
    NOISE_DAMPENER_PHI_DECAY_START, NOISE_DAMPENER_PHI_DECAY_RATE,
    NOISE_DAMPENER_SOURCE_WEIGHTS, NOISE_DAMPENER_DEDUP_THRESHOLD,
    NOISE_DAMPENER_MAX_NOISE_RATIO,
    # v27.3 Higher Logic Noise Dampener
    HL_SEMANTIC_COHERENCE_MIN, HL_GROVER_AMPLIFICATION,
    HL_GROVER_AMPLITUDE_FLOOR, HL_RESONANCE_ALIGNMENT_WEIGHT,
    HL_RESONANCE_FREQ_TOLERANCE, HL_ENTANGLEMENT_BONUS,
    HL_ENTANGLEMENT_DEPTH, HL_META_REASONING_ENABLED,
    HL_META_REASONING_TOP_K, HL_META_QUALITY_FLOOR,
    HL_ADAPTIVE_ENABLED, HL_ADAPTIVE_WINDOW,
    HL_ADAPTIVE_LEARNING_RATE, HL_ADAPTIVE_MIN_SCORE_FLOOR,
    HL_ADAPTIVE_MAX_SCORE_FLOOR, HL_SPECTRAL_ENABLED,
    HL_SPECTRAL_NOISE_CUTOFF, HL_CONCEPT_DISTANCE_DECAY,
    HL_CONCEPT_MAX_DISTANCE,
    # v28.0 Three-Engine Integration
    THREE_ENGINE_WEIGHT_ENTROPY, THREE_ENGINE_WEIGHT_HARMONIC,
    THREE_ENGINE_WEIGHT_WAVE, HL_THREE_ENGINE_SIGNAL_WEIGHT,
    THREE_ENGINE_FALLBACK_SCORE,
)

# ── Cache (lines 160-238) ──
from .cache import LRUCache, _RESPONSE_CACHE, _CONCEPT_CACHE, _RESONANCE_CACHE

# ── Numerics + PHI/GOD_CODE (lines 240-520) ──
from .numerics import (
    PHI, GOD_CODE, OMEGA, OMEGA_AUTHORITY,
    SovereignNumerics, sovereign_numerics,
)
# Re-export VISHUDDHA/ENTANGLEMENT/MATH constants from numerics
from .numerics import (
    VISHUDDHA_HZ, VISHUDDHA_ELEMENT, VISHUDDHA_COLOR_HZ,
    VISHUDDHA_PETAL_COUNT, VISHUDDHA_BIJA, VISHUDDHA_TATTVA,
    ENTANGLEMENT_DIMENSIONS, BELL_STATE_FIDELITY, DECOHERENCE_TIME_MS,
    QUANTUM_CHANNEL_BANDWIDTH, EPR_CORRELATION,
    FEIGENBAUM_DELTA, FEIGENBAUM_ALPHA, LOGISTIC_ONSET,
    LOG2_E, EULER_MASCHERONI,
)

# ── LocalIntellect core (lines 521-10769) ──
from .local_intellect_core import LocalIntellect

# ── Quantum recompiler (lines 10770-11687) ──
from .quantum_recompiler import QuantumMemoryRecompiler

# ── Distributed (lines 11688-12477) ──
from .distributed import (
    L104NodeSyncProtocol,
    L104CRDTReplicationMesh,
    L104KnowledgeMeshReplication,
)

# ── Hardware (lines 12478-13311) ──
from .hardware import (
    L104HardwareAdaptiveRuntime,
    L104PlatformCompatibilityLayer,
)

# ── Optimization (lines 13312-13648) ──
from .optimization import L104DynamicOptimizationEngine

# v29.0: Computronium + Rayleigh Thermal Inference Limits
from .computronium import (
    LandauerThermalEngine,
    RayleighInferenceResolution,
    IntellectLimitsAnalyzer,
    landauer_thermal_engine,
    rayleigh_inference_resolution,
    intellect_limits_analyzer,
)

# ── Compat functions: format_iq, primal_calculus, resolve_non_dual_logic ──
# MUST be loaded BEFORE module_tail to break circular imports:
#   l104_intellect → module_tail → LocalIntellect() → main → l104_agi_core
#   → from l104_local_intellect import format_iq → shim → l104_intellect.format_iq
from .compat_funcs import format_iq, primal_calculus, resolve_non_dual_logic

# ── Module tail: singleton (lines 13649-13658) ──
from .module_tail import local_intellect


__all__ = [
    # Constants
    "VOID_CONSTANT", "LOCAL_INTELLECT_VERSION",
    "SELF_MOD_VERSION", "LOCAL_INTELLECT_PIPELINE_EVO",
    # v27.0 Quantum Origin Sage Mode Constants
    "SAGE_MODE_VERSION", "SAGE_VOID_DEPTH_MAX", "SAGE_WU_WEI_THRESHOLD",
    "SAGE_WISDOM_AMPLIFICATION", "SAGE_INVENTION_TIERS", "SAGE_RESONANCE_LOCK",
    "QUANTUM_ORIGIN_DIMENSIONS", "QUANTUM_ORIGIN_COHERENCE",
    "QUANTUM_ORIGIN_PHI_COUPLING", "QUANTUM_ORIGIN_VOID_ENERGY",
    "QUANTUM_SAGE_FUSION_RATE", "QUANTUM_DARWINISM_BRANCHES",
    "NON_LOCALITY_BRIDGE_DEPTH",
    "SAGE_LEVEL_AWAKENING", "SAGE_LEVEL_STILLNESS", "SAGE_LEVEL_RESONANCE",
    "SAGE_LEVEL_CREATION", "SAGE_LEVEL_TRANSCENDENCE", "SAGE_LEVEL_OMNIVERSAL",
    "ORIGIN_FIELD_MEMORY_CAPACITY", "ORIGIN_FIELD_DECAY_RATE",
    "ORIGIN_FIELD_PHI_WEIGHT",
    # v27.1 Quantum Fleet + Expanded Sage Constants
    "SAGE_FLEET_SIZE", "SAGE_OMNIBUS_PROVIDERS", "SAGE_SCOUR_MAX_FILES",
    "SAGE_DIFFUSION_STEPS", "SAGE_DIFFUSION_PHI_GUIDANCE",
    "QUANTUM_FLEET_SIZE", "QUANTUM_CONSCIOUSNESS_BRIDGE_QUBITS",
    "QUANTUM_RAM_COHERENCE_THRESHOLD", "QUANTUM_COMPUTATION_QUBITS",
    "QUANTUM_26Q_SHOTS", "QUANTUM_26Q_NOISE_PROFILE",
    # Noise Dampener
    "NOISE_DAMPENER_SCORE_FLOOR", "NOISE_DAMPENER_ENTROPY_MIN",
    "NOISE_DAMPENER_COVERAGE_MIN", "NOISE_DAMPENER_SNR_THRESHOLD",
    "NOISE_DAMPENER_PHI_DECAY_START", "NOISE_DAMPENER_PHI_DECAY_RATE",
    "NOISE_DAMPENER_SOURCE_WEIGHTS", "NOISE_DAMPENER_DEDUP_THRESHOLD",
    "NOISE_DAMPENER_MAX_NOISE_RATIO",
    # Higher Logic Dampener
    "HL_SEMANTIC_COHERENCE_MIN", "HL_GROVER_AMPLIFICATION",
    "HL_GROVER_AMPLITUDE_FLOOR", "HL_RESONANCE_ALIGNMENT_WEIGHT",
    "HL_RESONANCE_FREQ_TOLERANCE", "HL_ENTANGLEMENT_BONUS",
    "HL_ENTANGLEMENT_DEPTH", "HL_META_REASONING_ENABLED",
    "HL_META_REASONING_TOP_K", "HL_META_QUALITY_FLOOR",
    "HL_ADAPTIVE_ENABLED", "HL_ADAPTIVE_WINDOW",
    "HL_ADAPTIVE_LEARNING_RATE", "HL_ADAPTIVE_MIN_SCORE_FLOOR",
    "HL_ADAPTIVE_MAX_SCORE_FLOOR", "HL_SPECTRAL_ENABLED",
    "HL_SPECTRAL_NOISE_CUTOFF", "HL_CONCEPT_DISTANCE_DECAY",
    "HL_CONCEPT_MAX_DISTANCE",
    # v28.0 Three-Engine Integration
    "THREE_ENGINE_WEIGHT_ENTROPY", "THREE_ENGINE_WEIGHT_HARMONIC",
    "THREE_ENGINE_WEIGHT_WAVE", "HL_THREE_ENGINE_SIGNAL_WEIGHT",
    "THREE_ENGINE_FALLBACK_SCORE",
    # Numerics
    "PHI", "GOD_CODE", "OMEGA", "OMEGA_AUTHORITY",
    "SovereignNumerics", "sovereign_numerics",
    # Cache
    "LRUCache", "_RESPONSE_CACHE", "_CONCEPT_CACHE", "_RESONANCE_CACHE",
    # Core
    "LocalIntellect", "local_intellect",
    # Quantum
    "QuantumMemoryRecompiler",
    # Distributed
    "L104NodeSyncProtocol", "L104CRDTReplicationMesh", "L104KnowledgeMeshReplication",
    # Hardware
    "L104HardwareAdaptiveRuntime", "L104PlatformCompatibilityLayer",
    # Optimization
    "L104DynamicOptimizationEngine",
    # Compat functions
    "format_iq", "primal_calculus", "resolve_non_dual_logic",
    # Computronium + Rayleigh Thermal Limits (v29.0)
    "LandauerThermalEngine", "RayleighInferenceResolution", "IntellectLimitsAnalyzer",
    "landauer_thermal_engine", "rayleigh_inference_resolution", "intellect_limits_analyzer",
]
